# This file was generated by GoReleaser. DO NOT EDIT.
cask "nss" do
  on_macos do
    postflight_steps do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/nss"]
    end
  end

  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "030e7f1775359dd11766ec3f13b5b1f2e3bde78f704770ce74bee4380dee9817"
      url "https://github.com/naturalselectionsoftware/nss-cli/releases/download/v#{version}/nss_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7b3bf207802f2bdc515d1e8586234799f5a0d42097b5aee3854854de72470f33"
      url "https://github.com/naturalselectionsoftware/nss-cli/releases/download/v#{version}/nss_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "aa48d4057ac92cad827d73d4ed56b223974d84b66d55bcceba8532795f1707ed"
      url "https://github.com/naturalselectionsoftware/nss-cli/releases/download/v#{version}/nss_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "19346c8a97a0af1d33c133529fcf857c924880b5d59b64500a58cde2daabb421"
      url "https://github.com/naturalselectionsoftware/nss-cli/releases/download/v#{version}/nss_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nss"
  desc "Command-line client for NSS operational event APIs"
  homepage "https://github.com/naturalselectionsoftware/nss-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nss"

  # No zap stanza required
end
