# This file was generated by GoReleaser. DO NOT EDIT.
cask "nss" do
  on_macos do
    postflight_steps do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/nss"]
    end
  end

  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "70442921105a63ec32721b61df746838a9fc702a3b90df9e7a92b565375d1d0c"
      url "https://github.com/naturalselectionsoftware/nss-cli/releases/download/v0.1.0/nss_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ee823ca248a94b6fc6639bdfc3d6e6e7050b7b793043208342e7f029cb563727"
      url "https://github.com/naturalselectionsoftware/nss-cli/releases/download/v0.1.0/nss_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a0ba5a834246c7e75d516291c32181fbc22a19aa3f8ae87b9820260839c57b50"
      url "https://github.com/naturalselectionsoftware/nss-cli/releases/download/v0.1.0/nss_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a7c8991a94c5719563cb1c157ab32459026fb53cae400300fc235921fdc6503d"
      url "https://github.com/naturalselectionsoftware/nss-cli/releases/download/v0.1.0/nss_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nss"
  desc "Command-line client for NSS operational event APIs"
  homepage "https://github.com/naturalselectionsoftware/nss-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nss"

  # No zap stanza required
end
